### ISSUE TITLE
A strange phenomenon of SVO algorithm

### ISSUE THREAD

**Issue by WXFMAV** [dji-sdk/Guidance-SDK#19]
We developed a kind of SVO algorithm by applying Feature-Matching and PNP Algorithm, there is a strange phenomenon that our algorithm can give out the trajectory of MAV well if the MAV keeps going straight ahead. But the algorithm can not adapt with turning movement, that is, when the MAV turn around, the algorithm give out a wrong position.  We wonder if there is something obviously wrong with rotation matrix.  Is there anyone experienced this problem?  thanks.

**Comment by tangketan** [comment]
Implementing a good and robust VO system is not that easy. That's why we build Guidance for you: we want to make it easier to equip any device with a good and reliable VO system.
Just a tip, estimating rotation from visual features isn't reliable. If you read our paper on Guidance (CVPR 2015), you'll find that we use IMU's rotation matrix.
